import { Recipe } from "./models/recipe.model";

export const sample_recipes: Recipe[] = [
    {
        id: '1',
        title: 'Vegan Chocolate Chip Cookies',
        description: 'These vegan chocolate chip cookies are soft, chewy, and loaded with chocolate chips. They are easy to make and require just a few simple ingredients.',
        ingredients: [
        '1 cup (240ml) unsweetened almond milk',
        '1 tablespoon apple cider vinegar',
        '1/2 cup (100 grams) granulated sugar',
        '1/3 cup (80ml) melted coconut oil',
        '1 teaspoon vanilla extract',
        '1 1/2 cups (180 grams) all-purpose flour',
        '1 teaspoon baking powder',
        '1/2 teaspoon baking soda',
        '1/2 teaspoon salt',
        '1 cup (175 grams) vegan chocolate chips'
        ],
        instructions: [
        'Preheat oven to 350°F/180°C. Line a baking sheet with parchment paper.',
        'In a small bowl, whisk together the almond milk and apple cider vinegar and set aside for a few minutes to curdle.',
        'In a large mixing bowl, add the sugar, coconut oil, and vanilla extract. Mix until well combined.',
        'Add the flour, baking powder, baking soda, and salt to the mixing bowl. Mix until just combined.',
        'Stir in the chocolate chips.',
        'Use a cookie scoop or spoon to drop the dough onto the prepared baking sheet. Leave about 2 inches between each cookie.',
        'Bake for 12-15 minutes, or until the edges are golden brown.',
        'Remove from the oven and let cool on the baking sheet for 5 minutes before transferring to a wire rack to cool completely.'
        ],
        calories: 160,
        cookTime: '25min',
        yield: '12',
        stars: 4.0,
        vegan: true,
        freeSugar: false,
        tags: ['Dessert', 'Vega'],
        origins: ['American'],
        favorite: false,
        imageUrl: 'vegan-chocolate-chip-cookie.jpeg',
    },
    {
        id: '2',
        title: 'Spaghetti Bolognese',
        description: `This classic Spaghetti Bolognese recipe is hearty, flavorful, and comforting. It's an easy weeknight dinner that the whole family will love. Perfect for those chilly nights.`,
        ingredients: [
            '1 lb spaghetti',
            '2 tbsp olive oil',
            '1 onion, diced',
            '2 cloves of garlic, minced',
            '1 lb ground beef',
            '1 can (14.5 oz) diced tomatoes',
            '1 cup beef broth',
            '1 tsp dried basil',
            '1 tsp dried oregano',
            '1/2 tsp salt',
            '1/4 tsp black pepper',
            '1/4 cup grated Parmesan cheese',
        ],
        instructions: [
        'Cook the spaghetti according to package directions until al dente. Drain and set aside.',
        'In a large pan, heat the olive oil over medium heat. Add the onion and garlic and sauté for 3 minutes.',
        'Add the ground beef and cook until browned, about 5 minutes.',
        'Add the diced tomatoes, beef broth, basil, oregano, salt, and pepper. Stir to combine.',
        'Bring the mixture to a simmer and let cook for 15-20 minutes, or until the sauce has thickened.',
        'Add the cooked spaghetti to the sauce and toss to combine.',
        'Sprinkle with grated Parmesan cheese and serve.'
        ],
        calories: 456,
        cookTime: '30min',
        yield: '4',
        stars: 4.0,
        vegan: false,
        freeSugar: false,
        tags: ['Main Course', 'Dinner'],
        origins: ['Italian'],
        favorite: false,
        imageUrl: 'spaghetti-bolognese.jpg',
    },
    {
        id: '3',
        title: 'Couscous Tfaya',
        description: 'Couscous Tfaya is a traditional Moroccan dish made with steamed couscous, caramelized onions and raisins, and a savory lamb or chicken stew. It is a hearty and flavorful meal that is perfect for any occasion.',
        ingredients: [
        '1 lb lamb or chicken, cut into cubes',
        '2 cups couscous',
        '2 onions, thinly sliced',
        '1/2 cup raisins',
        '1 tsp ground cumin',
        '1 tsp ground ginger',
        '1 tsp ground cinnamon',
        '1 tsp ground turmeric',
        '1 tsp paprika',
        '1/2 tsp saffron threads',
        'Salt and pepper to taste',
        '1/4 cup olive oil',
        '3 cups chicken or lamb broth'
        ],
        instructions: [
        'In a large pot, heat the olive oil over medium heat. Add the lamb or chicken and cook until browned on all sides.',
        'Add the onions, raisins, and spices to the pot and cook for an additional 5 minutes.',
        'Pour in the broth and bring the mixture to a boil. Reduce the heat to low and simmer for 45 minutes, or until the meat is cooked through.',
        'In a separate pot, bring 2 cups of water to a boil. Stir in the couscous and remove from heat. Cover and let sit for 5 minutes.',
        'Fluff the couscous with a fork and spoon it onto a serving platter.',
        'Spoon the stew over the couscous and serve.'
        ],
        calories: 800,
        cookTime: '1h 30min',
        yield: '4-6',
        stars: 4.5,
        vegan: false,
        freeSugar: true,
        tags: ['Main Dish', 'Moroccan'],
        origins: ['Moroccan'],
        favorite: false,
        imageUrl: 'couscous-tfaya.jpg'
    },
    {
        id: "4",
        title: 'Koshary',
        description: 'A traditional Egyptian dish made with lentils, macaroni, and rice topped with a spicy tomato sauce.',
        ingredients: [
            '1 cup lentils, cooked',
            '1 cup macaroni, cooked',
            '1 cup rice, cooked',
            '1 cup tomato sauce',
            '1/4 cup onion, diced',
            '2 cloves garlic, minced',
            '1 teaspoon cumin powder',
            '1 teaspoon chili powder',
            '1/4 cup parsley, chopped (optional)'
        ],
        instructions: [
        'In a pan, sauté the onion and garlic until softened.',
        'Add the cumin and chili powder and stir for a few seconds.',
        'Add the tomato sauce and bring the mixture to a boil.',
        'Add the cooked lentils, macaroni, and rice to the pan and stir to combine.',
        'Serve the koshary in bowls and top with parsley (if using).'
        ],
        calories: 500,
        cookTime: '30 min',
        yield: '4',
        stars: 4.7,
        vegan: true,
        freeSugar: true,
        tags: ['Egyptian', 'Main Course'],
        origins: ['Egypt'],
        favorite: false,
        imageUrl: "koshary.jpg"
    },
    {
        id: '5',
        title: 'Harira',
        description: 'Harira is a traditional Moroccan soup made with tomatoes, lentils, chickpeas, and a variety of spices. It is often served during Ramadan as a way to break the fast. The soup can be made thick or thin depending on personal preference.',
        ingredients: [
        '1 cup (200 grams) lentils, rinsed and drained',
        '1 cup (200 grams) chickpeas, rinsed and drained',
        '1/2 cup (100 grams) vermicelli noodles',
        '1 onion, chopped',
        '4 cloves of garlic, minced',
        '1 can (800 grams) of diced tomatoes',
        '2 cups (500 ml) of chicken or vegetable stock',
        '1 teaspoon ground cumin',
        '1 teaspoon ground ginger',
        '1 teaspoon ground turmeric',
        '1 teaspoon ground cinnamon',
        '1/2 teaspoon ground black pepper',
        'Salt to taste',
        '1 tablespoon olive oil',
        '1/4 cup (15 grams) fresh cilantro, chopped'
        ],
        instructions: [
        'In a large pot, heat the olive oil over medium heat. Add the onion and garlic and sauté until softened.',
        'Add the cumin, ginger, turmeric, cinnamon, and black pepper and sauté for another minute.',
        'Add the diced tomatoes, lentils, chickpeas, and stock. Bring to a boil, then reduce the heat and simmer for about 30 minutes, or until the lentils are tender.',
        'Add the vermicelli noodles and continue to simmer for another 10 minutes, or until the noodles are cooked.',
        'Add salt to taste and stir in the cilantro.',
        'Serve the harira hot, garnished with additional cilantro if desired.'
        ],
        calories: 267,
        cookTime: '45min',
        yield: '6',
        stars: 4,
        vegan: true,
        freeSugar: true,
        tags: ['Soup','Vegan'],
        origins: ['Moroccan'],
        favorite: false,
        imageUrl: 'Harira.jpg'
    },
    {
        id: '6',
        title: 'Tagine of Lamb with Dried Apricots and Prunes',
        description: 'This traditional Moroccan dish is a delicious combination of tender lamb, sweet dried apricots, and plump prunes, all slow-cooked together in a flavorful broth. Serve it with a side of couscous or rice for a complete meal.',
        ingredients: [
        '2 lbs boneless lamb, cut into 2-inch chunks',
        '1 onion, finely chopped',
        '3 cloves of garlic, minced',
        '1 teaspoon ground ginger',
        '1 teaspoon ground cumin',
        '1 teaspoon ground cinnamon',
        '1/2 teaspoon ground black pepper',
        '1/4 teaspoon ground saffron',
        '1 cup chicken broth',
        '1/2 cup dried apricots',
        '1/2 cup prunes, pitted',
        '1/4 cup chopped fresh cilantro',
        '1/4 cup chopped fresh parsley',
        'Salt and pepper to taste',
        '1 tablespoon olive oil'
        ],
        instructions: [
        'In a large pot or Dutch oven, heat the olive oil over medium-high heat. Add the lamb and brown on all sides, about 5 minutes.',
        'Add the onion and garlic to the pot and cook until softened, about 3 minutes.',
        'Stir in the ginger, cumin, cinnamon, black pepper, and saffron and cook for 1 minute.',
        'Add the chicken broth, dried apricots, and prunes to the pot and bring to a boil. Reduce the heat to low and simmer, covered, for 1 1/2 hours, or until the lamb is tender.',
        'Stir in the cilantro and parsley and season with salt and pepper to taste.',
        'Serve the tagine over couscous or rice and garnish with additional cilantro and parsley if desired.'
        ],
        calories: 546,
        cookTime: '2 hours',
        yield: '4',
        stars: 4.5,
        vegan: false,
        freeSugar: false,
        tags: ['Lamb', 'Tagine'],
        origins: ['Moroccan'],
        favorite: false,
        imageUrl: 'Tagine-of-Lamb-with-dried-apricots-and-prunes.jpg'
    },
    {
        id: '7',
        title: "Moroccan Mint Tea",
        description: "This sweet and refreshing tea is a staple of Moroccan culture. Made with green tea and fresh mint, it's the perfect drink to enjoy any time of day.",
        ingredients: [
        "4 cups water",
        "3 green tea bags",
        "1/4 cup fresh mint leaves",
        "1/4 cup sugar"
        ],
        instructions: [
        "In a small pot, bring the water to a boil.",
        "Add the tea bags and mint leaves and let steep for 5 minutes.",
        "Remove the tea bags and mint leaves and stir in the sugar until dissolved.",
        "Pour the tea into glasses and serve hot or cold."
        ],
        calories: 50,
        cookTime: "10 min",
        yield: "4",
        stars: 4.5,
        vegan: true,
        freeSugar: true,
        tags: ["Beverage"],
        origins: ["Moroccan"],
        favorite: false,
        imageUrl: "Moroccan-mint-tea.jpg"
    },
    {
        id: '8',
        title: 'Lasagna Bolognese',
        description: `This traditional lasagna Bolognese recipe is made with a rich meat sauce and layers of pasta, bechamel sauce, and Parmesan cheese. It's comforting, hearty, and perfect for a family dinner.`,
        ingredients: [
        '1 pound lasagna noodles',
        '1 pound ground beef',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 (28-ounce) can crushed tomatoes',
        '1 cup beef broth',
        '1 teaspoon dried basil',
        '1 teaspoon dried oregano',
        '1/4 teaspoon red pepper flakes',
        'Salt and pepper, to taste',
        '1 cup whole milk',
        '4 tablespoons unsalted butter',
        '4 tablespoons all-purpose flour',
        '1/4 teaspoon nutmeg',
        '1 cup grated Parmesan cheese',
        '1 cup grated mozzarella cheese',
        'Fresh parsley, chopped, for garnish'
        ],
        instructions: [
        'For the meat sauce:',
        'Cook the lasagna noodles according to package instructions until al dente. Drain and set aside.',
        'In a large pot or Dutch oven, brown the ground beef over medium-high heat. Drain off any excess fat.',
        'Add the onion and garlic and sauté until softened, about 5 minutes.',
        'Add the crushed tomatoes, beef broth, basil, oregano, red pepper flakes, and salt and pepper.',
        'Bring the sauce to a simmer and let it cook for 20-30 minutes, or until thickened.',
        'For the bechamel sauce:',
        'In a medium saucepan, heat the milk over medium heat until just simmering.',
        'In a separate saucepan, melt the butter over medium heat.',
        'Stir in the flour and cook, stirring constantly, for 1-2 minutes, or until the mixture forms a paste.',
        'Slowly pour in the hot milk, whisking constantly to prevent lumps.',
        'Bring the mixture to a simmer and cook for 2-3 minutes, or until thickened.',
        'Remove from heat and stir in the nutmeg and Parmesan cheese.',
        'To assemble the lasagna:',
        'Preheat the oven to 375°F/190°C.',
        'Spread a thin layer of meat sauce on the bottom of a 9x13 inch baking dish.',
        'Arrange a single layer of lasagna noodles on top of the sauce.',
        'Spread a layer of bechamel sauce over the noodles, followed by a layer of meat sauce and a sprinkle of mozzarella cheese.',
        'Repeat the layers, ending with a final layer of meat sauce and a sprinkle of mozzarella cheese.',
        'Cover the dish with foil and bake for 25 minutes.',
        'Remove the foil and bake for an additional 25-30 minutes, or until the cheese is golden and bubbly.',
        'Let the lasagna cool for 10-15 minutes before slicing and serving. Garnish with chopped parsley before serving.'
        ],
        calories: 667,
        cookTime: '1h 30min',
        yield: '8',
        stars: 4.7,
        vegan: false,
        freeSugar: false,
        tags: ["Dinner", "Italian"],
        origins: ["Italian"],
        favorite: false,
        imageUrl: "Lasagna-bolognese.jpg"
    },
    {
        id: '9',
        title: 'Kung Pao Chicken',
        description: 'Kung Pao chicken is a spicy Sichuan dish made with chicken, peanuts, vegetables, and chili peppers in a spicy sauce.',
        ingredients: [
        '1 pound boneless, skinless chicken breast, cut into small cubes',
        '1/4 cup corn starch',
        '2 tablespoons vegetable oil',
        '1/4 cup roasted peanuts',
        '1/4 cup diced bell peppers',
        '1/4 cup diced onion',
        '1 tablespoon minced garlic',
        '1 tablespoon minced ginger',
        '2 tablespoons soy sauce',
        '2 tablespoons rice vinegar',
        '1 tablespoon sugar',
        '1 teaspoon sesame oil',
        '1 teaspoon chili flakes',
        '1/4 cup chicken broth',
        '1 tablespoon corn starch',
        '1 tablespoon water'
        ],
        instructions: [
        'In a small bowl, mix together 1/4 cup corn starch and 1/4 cup water. Add the chicken and toss to coat.',
        'In a large skillet or wok, heat the oil over high heat. Add the chicken and cook, stirring, until browned and cooked through.',
        'Add the peanuts, bell peppers, onion, garlic, and ginger and stir-fry for 1-2 minutes.',
        'In a small bowl, mix together the soy sauce, rice vinegar, sugar, sesame oil, chili flakes, chicken broth, 1 tablespoon corn starch, and 1 tablespoon water.',
        'Add the sauce to the skillet and stir-fry until the sauce thickens and the vegetables are tender.',
        'Serve with rice.'
        ],
        calories: 400,
        cookTime: '30min',
        yield: '4',
        stars: 4,
        vegan: false,
        freeSugar: false,
        tags: ['Main course','Chinese'],
        origins: ['Chinese'],
        favorite: false,
        imageUrl: 'Kung-pao-chicken.jpg',
    },
    {
        id: '10',
        title: 'Egg Fried Rice',
        description: 'Egg Fried Rice is a classic Chinese dish that is simple to make, but packed with flavor. It is made with fluffy rice, scrambled eggs, and a variety of vegetables, making it a well-balanced meal that is perfect for any occasion.',
        ingredients: [
            '3 cups cooked white rice',
            '2 tablespoons vegetable oil',
            '2 eggs, lightly beaten',
            '1/2 cup diced carrots',
            '1/2 cup diced bell peppers',
            '1/2 cup frozen peas',
            '2 green onions, thinly sliced',
            '2 cloves garlic, minced',
            '2 tablespoons soy sauce',
            '1 tablespoon sesame oil',
            'Salt and pepper to taste'
        ],
        instructions: [
            'Heat the oil in a large skillet over medium heat.',
            'Add the eggs and scramble until cooked through.',
            'Remove the eggs from the skillet and set aside.',
            'Add the diced carrots, bell peppers, and frozen peas to the skillet and sauté for 5 minutes, or until tender.',
            'Add the green onions and garlic to the skillet and sauté for an additional 2 minutes.',
            'Add the cooked rice to the skillet and stir to combine.',
            'Add the soy sauce and sesame oil to the skillet and stir to combine.',
            'Add the scrambled eggs back to the skillet and stir to combine.',
            'Season with salt and pepper to taste.',
            'Serve the egg fried rice hot, garnished with green onions and sesame seeds if desired.'
        ],
        calories: 225,
        cookTime: '30 minutes',
        yield: '4 servings',
        stars: 4,
        vegan: false,
        freeSugar: false,
        tags: ['Main Dish', 'Chinese'],
        origins: ['Chinese'],
        favorite: false,
        imageUrl: 'egg-fried-rice.jpg'
    },
    {
        id: '11',
        title: 'Mojito',
        description: 'The mojito is a classic Cuban cocktail that has become a staple at bars around the world. It is a refreshing blend of mint, lime, and rum that is perfect for sipping on a hot summer day.',
        ingredients: [
        '10 fresh mint leaves',
        '1/2 lime, cut into wedges',
        '2 tablespoons white sugar',
        '1 cup ice cubes',
        '1 1/2 ounces white rum',
        '1/2 cup club soda'
        ],
        instructions: [
        'In a tall glass, muddle the mint leaves, lime wedges, and sugar until the mint leaves are bruised and the lime juice is extracted.',
        'Fill the glass with ice cubes.',
        'Pour the rum and club soda over the ice.',
        'Stir well, and garnish with a lime wedge and a mint sprig.'
        ],
        calories: 150,
        cookTime: '5min',
        yield: '1',
        stars: 4.5,
        vegan: true,
        freeSugar: false,
        tags: ['Cocktail'],
        origins: ['Cuban'],
        favorite: false,
        imageUrl: 'Mojito.jpg'
    },
    {
        id: '12',
        title: 'Margarita',
        description: 'A classic margarita is a simple and refreshing cocktail that is perfect for any occasion. It is made with tequila, lime juice, and orange liqueur.',
        ingredients: [
        '1 1/2 ounces tequila',
        '3/4 ounce lime juice',
        '1/2 ounce Cointreau or other orange liqueur',
        'Salt for rimming glass',
        'Lime wheel for garnish'
        ],
        instructions: [
        'Rim a chilled glass with salt.',
        'In a shaker filled with ice, combine the tequila, lime juice, and orange liqueur.',
        'Shake well and strain into the salt-rimmed glass.',
        'Garnish with a lime wheel.'
        ],
        calories: 150,
        cookTime: '5min',
        yield: '1',
        stars: 4.0,
        vegan: true,
        freeSugar: false,
        tags: ['Cocktail'],
        origins: ['Mexican'],
        favorite: false,
        imageUrl: 'margarita.jpg'
    },
    {
        id: '13',
        title: 'Old Fashioned',
        description: 'A classic cocktail made with whiskey, sugar, and bitters. A perfect drink for a sophisticated evening.',
        ingredients: [
        '2 oz whiskey',
        '1/4 oz simple syrup',
        '2 dashes bitters',
        'orange peel for garnish'
        ],
        instructions: [
        'In a mixing glass, combine the whiskey, simple syrup, and bitters.',
        'Stir the mixture with ice until chilled.',
        'Strain the mixture into a glass filled with ice.',
        'Garnish with an orange peel.'
        ],
        calories: 150,
        cookTime: '5 min',
        yield: '1',
        stars: 4.4,
        vegan: true,
        freeSugar: false,
        tags: ['Cocktail', 'Alcoholic'],
        origins: ['American'],
        favorite: false,
        imageUrl: 'old-fashioned.jpg'
    },
    {
        id: "14",
        title: "Green Juice",
        description: "A healthy and refreshing juice made with a combination of leafy greens, cucumber, and lemon.",
        ingredients: [
        "1 cup kale",
        "1 cup spinach",
        "1/2 cucumber",
        "1 lemon, juiced",
        "1/2 cup water"
        ],
        instructions: [
        "Wash and chop the kale, spinach, and cucumber.",
        "In a blender, combine the kale, spinach, cucumber, lemon juice, and water.",
        "Blend until smooth.",
        "Strain through a fine-mesh sieve or cheesecloth, if desired.",
        "Pour into a glass and enjoy immediately."
        ],
        calories: 50,
        cookTime: "5 min",
        yield: "1",
        stars: 4.7,
        vegan: true,
        freeSugar: true,
        favorite: false,
        tags: ["Juice", "Healthy", "Vegan"],
        origins: ["American", "California"],
        imageUrl: "green-juice.jpg"
    },
    {
        id: "15",
        title: "Carrot Juice",
        description: "A sweet and delicious juice made with fresh carrots and ginger.",
        ingredients: [
            "4 medium carrots",
            "1/2 inch ginger",
            "1/2 cup water"
        ],
        instructions: [
            "Wash and chop the carrots.",
            "Peel and chop the ginger.",
            "In a blender, combine the carrots, ginger and water.",
            "Blend until smooth.",
            "Strain through a fine-mesh sieve or cheesecloth, if desired.",
            "Pour into a glass and enjoy immediately."
        ],
        calories: 70,
        cookTime: "5 min",
        yield: "1",
        stars: 4.5,
        vegan: true,
        freeSugar: true,
        tags: ["Juice", "Healthy", "Vegan"],
        origins: ["Chinese"],
        favorite: false,
        imageUrl: "carrot-juice.jpg"
    },
    {
        id: "16",
        title: "Beet Juice",
        description: "A vibrant and nutritious juice made with fresh beets, apple and lemon.",
        ingredients: [
        "1 medium beet",
        "1 medium apple",
        "1/2 lemon, juiced",
        "1/2 cup water"
        ],
        instructions: [
        "Wash and chop the beet, apple.",
        "In a blender, combine the beets, apple, lemon juice, and water.",
        "Blend until smooth.",
        "Strain through a fine-mesh sieve or cheesecloth, if desired.",
        "Pour into a glass and enjoy immediately."
        ],
        calories: 80,
        cookTime: "5 min",
        yield: "1",
        stars: 4.3,
        vegan: true,
        freeSugar: true,
        tags: ["Juice", "Healthy", "Vegan"],
        origins: ["Europe"],
        favorite: false,
        imageUrl: "beet-juice.jpg"
    },
    {
        id: "17",
        title: 'Strawberry Banana Smoothie',
        description: 'A delicious and refreshing smoothie made with fresh strawberries, banana, and Greek yogurt.',
        ingredients: [
            '1 cup fresh strawberries, hulled and halved',
            '1 banana, peeled and sliced',
            '1/2 cup Greek yogurt',
            '1/4 cup orange juice',
            '1 tablespoon honey (optional)'
        ],
        instructions: [
        'Add all ingredients to a blender and blend until smooth.',
        'Pour into a glass and enjoy immediately.'
        ],
        calories: 250,
        cookTime: '5 min',
        yield: '1',
        stars: 4.8,
        vegan: false,
        freeSugar: true,
        tags: ['Smoothie', 'Breakfast'],
        origins: ['American'],
        favorite: false,
        imageUrl: "strawberry-banana-smoothie.jpg"
    },
    {
        id: "18",
        title: 'Blueberry Peach Smoothie',
        description: 'A tasty and nutritious smoothie made with fresh blueberries, peaches, and almond milk.',
        ingredients: [
            '1 cup fresh blueberries',
            '1 peach, pitted and sliced',
            '1/2 cup almond milk',
            '1/4 cup orange juice',
            '1 tablespoon honey (optional)'
        ],
        instructions: [
            'Add all ingredients to a blender and blend until smooth.',
            'Pour into a glass and enjoy immediately.'
        ],
        calories: 200,
        cookTime: '5 min',
        yield: '1',
        stars: 4.5,
        vegan: true,
        freeSugar: false,
        tags: ['Smoothie', 'Breakfast'],
        origins: ['American'],
        favorite: false,
        imageUrl: "blueberry-peach-smoothie.jpeg"
    },
    {
        id: "19",
        title: 'Mango Pineapple Smoothie',
        description: 'A tropical and refreshing smoothie made with fresh mango, pineapple, and coconut milk.',
        ingredients: [
            '1 cup fresh mango, peeled and diced',
            '1 cup fresh pineapple, peeled and diced',
            '1/2 cup coconut milk',
            '1/4 cup orange juice',
            '1 tablespoon honey (optional)'
        ],
        instructions: [
            'Add all ingredients to a blender and blend until smooth.',
            'Pour into a glass and enjoy immediately.'
        ],
        calories: 300,
        cookTime: '5 min',
        yield: '1',
        stars: 4.7,
        vegan: true,
        freeSugar: true,
        tags: ['Smoothie', 'Breakfast'],
        origins: ['Tropical'],
        favorite: false,
        imageUrl: "mango-pineapple-smoothie.jpg"
    },
    {
        id: "20",
        title: 'Chocolate Peanut Butter Smoothie',
        description: 'A rich and decadent smoothie made with cocoa powder, peanut butter, and almond milk.',
        ingredients: [
            '1/4 cup cocoa powder',
            '2 tablespoons peanut butter',
            '1 banana, peeled and sliced',
            '1/2 cup almond milk',
            '1/4 cup orange juice'
        ],
        instructions: [
            'Add all ingredients to a blender and blend until smooth.',
            'Pour into a glass and enjoy immediately.'
        ],
        calories: 350,
        cookTime: '5 min',
        yield: '1',
        stars: 4.9,
        vegan: false,
        freeSugar: false,
        tags: ['Smoothie', 'Dessert'],
        origins: ['American'],
        favorite: false,
        imageUrl: "chocolate-peanut-butter-smoothie.jpg"
    },
    {
        id: "21",
        title: 'Ful Medames',
        description: 'A popular Egyptian breakfast dish made with cooked fava beans, garlic, and lemon juice.',
        ingredients: [
            '1 cup fava beans, cooked',
            '1/4 cup onion, diced',
            '2 cloves garlic, minced',
            '1/4 cup lemon juice',
            '1/4 cup parsley, chopped (optional)',
            '1/4 cup tahini (optional)',
            'Salt and pepper to taste'
        ],
        instructions: [
            'In a pan, sauté the onion and garlic until softened.',
            'Add the cooked fava beans to the pan and mash them slightly with a fork.',
            'Add the lemon juice, parsley (if using), tahini (if using), and salt and pepper to the pan and stir to combine.',
            'Serve the ful medames in bowls or as a spread on bread.'
        ],
        calories: 300,
        cookTime: '15 min',
        yield: '2',
        stars: 4.8,
        vegan: true,
        freeSugar: true,
        tags: ['Egyptian', 'Breakfast'],
        origins: ['Egypt'],
        favorite: false,
        imageUrl: "ful-medames.jpeg"
    }
    
    
]